version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    volumes:
      - ./mongo/graylog-mongo-init.js:/docker-entrypoint-initdb.d/graylog-mongo-init.js:ro
#      todo: you can add 'mongo.conf' configurations here if you need.
#      - ./mongo:/conf/
#    command: "mongod --config /conf/mongo.conf"
    networks:
      - graylog

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressroot
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
      ME_CONFIG_MONGODB_AUTH_USERNAME: mongoroot
      ME_CONFIG_MONGODB_AUTH_PASSWORD: mongopass
      ME_CONFIG_MONGODB_URL: mongodb://mongoroot:mongopass@mongo:27017/
    depends_on:
      - mongo
    networks:
      - graylog


  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment :
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - http.cors.allow-origin=*
      - http.cors.enabled=true
      - discovery.type=single-node
    ports:
      - "9201:9201"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  #        command: [ 'chown', '-R', '1000:1000', '/usr/share/elasticsearch/data' ]

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.2
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=719d5ccdcc1cdb32a56f02055f5f0bc506479992e4f080c0d5218d03d9f5d22f
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_MONGODB_URI=mongodb://mongoroot:mongopass@mongo:27017/graylog
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
networks:
  graylog:
    driver: bridge